"""Tests for CSV to ISA-Tab conversion in ISAForge."""
from __future__ import annotations

import csv
from pathlib import Path

import pytest

from bioledger.forges.isaforge.builder import csv_to_isatab
from bioledger.forges.isaforge.dataset import load_dataset_from_isatab
from bioledger.forges.isaforge.validate import validate_isatab


def test_csv_to_isatab_basic(tmp_path: Path) -> None:
    """Test basic CSV to ISA-Tab conversion without LLM config."""
    # Create a simple CSV samplesheet
    csv_file = tmp_path / "samples.csv"
    with open(csv_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["sample_id", "organism", "reads_file"])
        writer.writerow(["S001", "Mus musculus", "S001_R1.fastq.gz"])
        writer.writerow(["S002", "Homo sapiens", "S002_R1.fastq.gz"])

    # Convert to ISA-Tab (no config = fallback mode)
    output_dir = tmp_path / "isatab"
    import asyncio
    result = asyncio.run(csv_to_isatab(csv_file, output_dir, config=None))

    # Verify output directory exists
    assert result.exists()
    assert result == output_dir

    # Verify ISA-Tab files were created (a_assay.txt may not be generated by isatools)
    assert (output_dir / "i_investigation.txt").exists()
    assert (output_dir / "s_study.txt").exists()
    assert (output_dir / "samples.csv").exists()  # Original preserved


def test_csv_to_isatab_validation(tmp_path: Path) -> None:
    """Test that generated ISA-Tab passes validation."""
    csv_file = tmp_path / "samples.csv"
    with open(csv_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["sample_id", "organism", "data_file"])
        writer.writerow(["S001", "E. coli", "data.txt"])

    output_dir = tmp_path / "isatab"
    import asyncio
    asyncio.run(csv_to_isatab(csv_file, output_dir, config=None))

    # Validate the generated ISA-Tab
    result = validate_isatab(output_dir)
    assert result.is_valid, f"Validation failed: {[i.message for i in result.issues]}"


def test_csv_to_isatab_dataset_loading(tmp_path: Path) -> None:
    """Test that generated ISA-Tab can be loaded as a DataSet."""
    csv_file = tmp_path / "samples.csv"
    with open(csv_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["sample_id", "organism", "reads_file"])
        writer.writerow(["S001", "Mus musculus", "S001_R1.fastq.gz"])
        writer.writerow(["S002", "Mus musculus", "S002_R1.fastq.gz"])
        writer.writerow(["S003", "Homo sapiens", "S003_R1.fastq.gz"])

    output_dir = tmp_path / "isatab"
    import asyncio
    asyncio.run(csv_to_isatab(csv_file, output_dir, config=None))

    # Load as DataSet
    dataset = load_dataset_from_isatab(output_dir, validate=False)

    # Verify dataset properties
    assert len(dataset.sample_metadata) == 3
    assert "S001" in dataset.sample_metadata
    assert "S002" in dataset.sample_metadata
    assert "S003" in dataset.sample_metadata

    # Organisms should be detected
    assert len(dataset.organisms) >= 1


def test_csv_to_isatab_no_organism_column(tmp_path: Path) -> None:
    """Test conversion when CSV has no organism column."""
    csv_file = tmp_path / "samples.csv"
    with open(csv_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["sample_id", "data_file"])
        writer.writerow(["S001", "file1.txt"])
        writer.writerow(["S002", "file2.txt"])

    output_dir = tmp_path / "isatab"
    import asyncio
    asyncio.run(csv_to_isatab(csv_file, output_dir, config=None))

    # Should still create valid ISA-Tab
    result = validate_isatab(output_dir)
    assert result.is_valid

    # Load and verify
    dataset = load_dataset_from_isatab(output_dir, validate=False)
    assert len(dataset.sample_metadata) == 2


def test_csv_to_isatab_study_file_content(tmp_path: Path) -> None:
    """Test that s_study.txt has correct structure."""
    csv_file = tmp_path / "samples.csv"
    with open(csv_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["sample_id", "organism"])
        writer.writerow(["S001", "Mus musculus"])
        writer.writerow(["S002", "Homo sapiens"])

    output_dir = tmp_path / "isatab"
    import asyncio
    asyncio.run(csv_to_isatab(csv_file, output_dir, config=None))

    # Read and verify s_study.txt structure
    study_file = output_dir / "s_study.txt"
    content = study_file.read_text()

    # Should have header with expected columns
    lines = content.strip().split("\n")
    assert len(lines) == 3  # header + 2 samples

    header = lines[0].split("\t")
    assert "Source Name" in header
    assert "Sample Name" in header

    # Each sample should have source and sample name
    for line in lines[1:]:
        parts = line.split("\t")
        assert len(parts) >= 2
        assert parts[0].startswith("source_")
        assert parts[-1] in ["S001", "S002"]
